CREATE TABLE [dbo].[UserPWD](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[PasswordSalt] [nvarchar](200) NOT NULL,
	[PasswordHash] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_UserPWD] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO